### ISSUE TITLE
avatar image size

### ISSUE THREAD

**Issue by y-nk** [fork-my-spoons/jira-issues.spoon#2]
Avatar image looks a bit big. Is there something to do for this?

![image](https://user-images.githubusercontent.com/411625/119938435-9df58b00-bfb6-11eb-8fee-d4ddfdf91d23.png)

**Comment by streetturtle** [comment]
Thanks for the issue!
I've fixed it, you can download the latest version here: https://github.com/fork-my-spoons/jira-issues.spoon/releases/tag/v1.2

**Comment by y-nk** [comment]
Thanks a lot @streetturtle !
